PAGE_SIZE = 6
PAGE_SIZE_QUERY_PARAM = 'limit'
RECIPE_INGREDIENT_EXTRA = 1
RECIPE_INGREDIENT_MIN_NUM = 1

MIN_COOKING_TIME = 1
MAX_COOKING_TIME = 32000
MIN_AMOUNT = 1
MAX_AMOUNT = 32000

MAX_LENGTH_RECIPES_NAME = 256
MAX_LENGTH_INGREDIENT_NAME = 128
MAX_LENGTH_MEASUREMENT = 64
MAX_LENGTH_TAG_NAME = 32
MAX_LENGTH_TAG_SLUG = 32
MAX_LENGTH_SHORTURL = 6
MAX_LENGTH_FIRSTNAME = 150
MAX_LENGTH_LASTNAME = 150
